config = {
    'node1': {'type': 'client', 'next': ('node4', 'node5', 'node6')},
    'node2': {'type': 'client', 'next': ('node4', 'node5', 'node6')},
    'node3': {'type': 'client', 'next': ('node4', 'node5', 'node6')},
    'node4': {'type': 'shim', 'next': 'node7', 'clients': ('node1', 'node2', 'node3')},
    'node5': {'type': 'shim', 'next': 'node8', 'clients': ('node1', 'node2', 'node3')},
    'node6': {'type': 'shim', 'next': 'node9', 'clients': ('node1', 'node2', 'node3')},
    'node7': {'type': 'mixer', 'next': 'node10', 'shim': 'node4'},
    'node8': {'type': 'mixer', 'next': 'node11', 'shim': 'node5'},
    'node9': {'type': 'mixer', 'next': 'node12', 'shim': 'node6'},
    'node10': {'type': 'exec', 'verifiers': ('node13', 'node14', 'node15'), 'shim': 'node4', 'peers': ('node11', 'node12')},
    'node11': {'type': 'exec', 'verifiers': ('node13', 'node14', 'node15'), 'shim': 'node5', 'peers': ('node10', 'node12')},
    'node12': {'type': 'exec', 'verifiers': ('node13', 'node14', 'node15'), 'shim': 'node6', 'peers': ('node10', 'node11')},
    'node13': {'type': 'verifier', 'execs': ('node10', 'node11', 'node12')},
    'node14': {'type': 'verifier', 'execs': ('node10', 'node11', 'node12')},
    'node15': {'type': 'verifier', 'execs': ('node10', 'node11', 'node12')},
}